### ISSUE TITLE
please add this embedded to this  github as a portfolio

### ISSUE THREAD

**Issue by mouser15** [spacestation13/website#116]
if you embed this as a portfolio then people with some form of block will be able to play it too, therfore expanding the community

**Comment by ZeWaka** [comment]
Not sure what you mean, what's a portfolio to you?

**Comment by mouser15** [comment]
i mean add it playable on the github page, i hink its called a portfolio but it would be nice to be embeded on this page as well as it is on the site, sorry i didnt respond sooner
